In [2]:
import numpy as np
import pandas as pd
%matplotlib inline
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [7]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
# convertinr target data is multi columns into single column
y=iris.target.reshape(-1,1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [38]:
from sklearn.preprocessing import OneHotEncoder
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
encoder

OneHotEncoder(sparse=False)

In [39]:
y = encoder.fit_transform(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [40]:
# split the data for trainig and testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.data,y,test_size=0.20)

In [54]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam,SGD,RMSprop

In [59]:
model=Sequential()
model.add(Dense(10,input_shape=(4,),activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(3,activation='softmax',name='output'))
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
#optimizer=SGD(learning_rate=0.001)
optimizer=RMSprop(learning_rate=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
#print('Neural Network Model Summary: ')
print(model.summary())

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 10)                50        
_________________________________________________________________
dense_15 (Dense)             (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


In [60]:
model.fit(x_train, y_train, verbose=2, batch_size=5, epochs=200)

Epoch 1/200
24/24 - 0s - loss: 2.0019 - accuracy: 0.3417
Epoch 2/200
24/24 - 0s - loss: 1.6807 - accuracy: 0.2583
Epoch 3/200
24/24 - 0s - loss: 1.4549 - accuracy: 0.1417
Epoch 4/200
24/24 - 0s - loss: 1.2812 - accuracy: 0.0000e+00
Epoch 5/200
24/24 - 0s - loss: 1.1632 - accuracy: 0.0583
Epoch 6/200
24/24 - 0s - loss: 1.0890 - accuracy: 0.2333
Epoch 7/200
24/24 - 0s - loss: 1.0400 - accuracy: 0.4083
Epoch 8/200
24/24 - 0s - loss: 1.0017 - accuracy: 0.4167
Epoch 9/200
24/24 - 0s - loss: 0.9662 - accuracy: 0.5000
Epoch 10/200
24/24 - 0s - loss: 0.9298 - accuracy: 0.6667
Epoch 11/200
24/24 - 0s - loss: 0.8892 - accuracy: 0.6750
Epoch 12/200
24/24 - 0s - loss: 0.8499 - accuracy: 0.8083
Epoch 13/200
24/24 - 0s - loss: 0.8132 - accuracy: 0.6917
Epoch 14/200
24/24 - 0s - loss: 0.7757 - accuracy: 0.6917
Epoch 15/200
24/24 - 0s - loss: 0.7355 - accuracy: 0.7167
Epoch 16/200
24/24 - 0s - loss: 0.6975 - accuracy: 0.7500
Epoch 17/200
24/24 - 0s - loss: 0.6634 - accuracy: 0.6833
Epoch 18/200
24/24 

Epoch 142/200
24/24 - 0s - loss: 0.0799 - accuracy: 0.9917
Epoch 143/200
24/24 - 0s - loss: 0.0795 - accuracy: 0.9917
Epoch 144/200
24/24 - 0s - loss: 0.0799 - accuracy: 0.9917
Epoch 145/200
24/24 - 0s - loss: 0.0786 - accuracy: 0.9917
Epoch 146/200
24/24 - 0s - loss: 0.0803 - accuracy: 0.9917
Epoch 147/200
24/24 - 0s - loss: 0.0788 - accuracy: 0.9833
Epoch 148/200
24/24 - 0s - loss: 0.0794 - accuracy: 0.9833
Epoch 149/200
24/24 - 0s - loss: 0.0769 - accuracy: 0.9833
Epoch 150/200
24/24 - 0s - loss: 0.0797 - accuracy: 0.9750
Epoch 151/200
24/24 - 0s - loss: 0.0809 - accuracy: 0.9833
Epoch 152/200
24/24 - 0s - loss: 0.0770 - accuracy: 0.9833
Epoch 153/200
24/24 - 0s - loss: 0.0788 - accuracy: 0.9917
Epoch 154/200
24/24 - 0s - loss: 0.0786 - accuracy: 0.9750
Epoch 155/200
24/24 - 0s - loss: 0.0773 - accuracy: 0.9917
Epoch 156/200
24/24 - 0s - loss: 0.0754 - accuracy: 0.9917
Epoch 157/200
24/24 - 0s - loss: 0.0786 - accuracy: 0.9833
Epoch 158/200
24/24 - 0s - loss: 0.0767 - accuracy: 0.99

In [61]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 1ms/step - loss: 0.0889 - accuracy: 0.9667


[0.08887247741222382, 0.9666666388511658]